name: Cache SDL for Ubuntu 3

# on: push

on:
  push: 
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

env:
  projectName: SDLOpenGL
  SDL_VERSION: 2.28.5

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Tool versions
      shell: bash
      run: | 
        echo g++ --version
        g++ --version
        echo 
        echo clang++ --version
        clang++ --version
        echo 
        echo cmake --version
        cmake --version
        echo 
        echo ninja --version
        ninja --version

    - name: Cache SDL2 into directory accessible without admin privileges # Ubuntu can't handle it otherwise!
      # id: accessible-SDL2-cache1
      id: SDL2-cache1
      uses: actions/cache@v3
      with:
        path: External/SDL2
        # path: ~/SDL2
        key: ${{ runner.os }}-SDL2-cache1

    - name: Install SDL2 if it is not cached and move it from /usr into ~/SDL2
      if: steps.SDL2-cache1.outputs.cache-hit != 'true'
      run: | 
        echo SDL2 is not yet cached therefore install it
        echo git clone --depth 1 https://github.com/libsdl-org/SDL.git External/SDL2
        git clone --depth 1 https://github.com/libsdl-org/SDL.git SDL2
        cd SDL2
        ./configure --prefix=../External/SDL2
        make
        make install
        find ../External/SDL2/ -iname SDL*config.cmake
      # echo ls ~/SDL2/usr/include
      # ls ~/SDL2/usr/include
      # echo ls ~/SDL2/usr/lib/x86_64-linux-gnu/cmake/SDL2
      # ls ~/SDL2/usr/lib/x86_64-linux-gnu/cmake/SDL2
      # echo ls ~/SDL2/usr/lib/x86_64-linux-gnu
      # ls ~/SDL2/usr/lib/x86_64-linux-gnu

    - name: CMake build --- Ninja, Gnu, Debug
      run: |
        echo ~~~ CMake configure ~~~
        echo cmake --preset Ninja-Gnu-Debug
        cmake --preset Ninja-Gnu-Debug
# echo cmake --preset Ninja-Gnu-Debug -D SDL2_DIR=/usr/lib/x86_64-linux-gnu/cmake/SDL2
# cmake --preset Ninja-Gnu-Debug -D SDL2_DIR=/usr/lib/x86_64-linux-gnu/cmake/SDL2

        echo 
        echo ~~~ CMake build ~~~
        echo cmake --build --preset Ninja-Gnu-Debug
        cmake --build --preset Ninja-Gnu-Debug

    - name: Show where SDL2 is cached
      run: |
        echo ls ~/SDL2/usr/include
        ls ~/SDL2/usr/include
        echo ls ~/SDL2/usr/lib/x86_64-linux-gnu/cmake/SDL2
        ls ~/SDL2/usr/lib/x86_64-linux-gnu/cmake/SDL2
        echo ls ~/SDL2/usr/lib/x86_64-linux-gnu
        ls ~/SDL2/usr/lib/x86_64-linux-gnu
