name: Caching Primes 3

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache Primes
      id: cache-primes
      uses: actions/cache@v3
      with:
        path: |
          path/to/dependencies
          some/other/dependencies/dummy?.txt
        key: ${{ runner.os }}-primes

    - name: Generate Prime Numbers
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: |
        mkdir -p path/to/dependencies
        mkdir -p some/other/dependencies
        touch path/to/dependencies/dummy1.txt
        touch some/other/dependencies/dummy2.txt
        touch some/other/dependencies/dummy3.txt
        echo This is step 1
        ls path/to/dependencies
        ls some/other/dependencies

    - name: Use Prime Numbers
      run: |
        echo This is step 2
        ls path/to/dependencies
        ls some/other/dependencies
