name: Caching Primes

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache Primes
      id: cache-primes
      uses: actions/cache@v3
      with:
        path: prime-numbers
        key: ${{ runner.os }}-primes

    - name: Generate Prime Numbers
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: |
        mkdir prime-numbers
        touch prime-numbers/dummy1.txt
        echo This is step 1
      # /generate-primes.sh -d prime-numbers

    - name: Use Prime Numbers
      run: |
        ls prime-numbers
        echo This is step 2
      # /primes.sh -d prime-numbers
