name: Build for MacOS, Ubuntu and Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, macos-11, windows-2022 ]
    steps:
      - uses: actions/checkout@v2

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/build
          key: ${{ matrix.os }}-build
          restore-keys: ${{ matrix.os }}-build

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DFORCE_COLORED_OUTPUT=1

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
