name: No cache SDL2 install 1

on:
  push: 
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

env:
  projectName: SDLOpenGL
  SDL_VERSION: 2.28.5

jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Install SDL2 but do NOT cache it (caching of SDL2 doesn't work on Ubuntu)
      run: |
        echo sudo apt-get install --yes libsdl2-dev
        sudo apt-get install --yes libsdl2-dev

        echo Find in /usr
        find /usr/ -iname SDL.h
        find /usr/ -iname libSDL2.a
        find /usr/ -iname libSDL2.so
        find /usr/ -iname SDL2?Config.cmake

        echo ls /usr/include/SDL2
        ls /usr/include/SDL2
        echo ls /usr/lib/x86_64-linux-gnu
        ls /usr/lib/x86_64-linux-gnu
        echo ls /usr/lib/x86_64-linux-gnu/cmake/SDL2
        ls /usr/lib/x86_64-linux-gnu/cmake/SDL2
        
    - name: CMake configure --- Ninja, Gnu, Debug
      run: |
        echo cmake --preset Ninja-Gnu-Debug
        cmake --preset Ninja-Gnu-Debug

    - name: CMake build --- Ninja, Gnu, Debug
      run: |
        echo cmake --build --preset Ninja-Gnu-Debug
        cmake --build  --preset Ninja-Gnu-Debug


  build-on-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Install SDL2 (do not cache)
      run: |
        echo brew install sdl2
        brew install sdl2

        find /usr/local/Cellar/sdl2 -iname SDL.h
        find /usr/local/Cellar/sdl2 -iname libSDL2.a
        find /usr/local/Cellar/sdl2 -iname libSDL2.so
        find /usr/local/Cellar/sdl2 -iname SDL2?Config.cmake
        
        echo ls /usr/local/Cellar/sdl2/2.28.5/include/SDL2
        ls /usr/local/Cellar/sdl2/2.28.5/include/SDL2
        echo ls /usr/local/Cellar/sdl2/2.28.5/lib
        ls /usr/local/Cellar/sdl2/2.28.5/lib
        echo ls /usr/local/Cellar/sdl2/2.28.5/lib/cmake/SDL2
        ls /usr/local/Cellar/sdl2/2.28.5/lib/cmake/SDL2

    - name: CMake configure --- Ninja, Clang, Debug
      run: |
        echo cmake --preset Ninja-Clang-Debug
        cmake --preset Ninja-Clang-Debug

    - name: CMake build --- Ninja, Clang, Debug
      run: |
        echo cmake --build --preset Ninja-Clang-Debug
        cmake --build --preset Ninja-Clang-Debug


  build-on-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup MSVC compiler
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Install SDL2 (do not cache)
      shell: powershell
      run: |
        Invoke-WebRequest "https://github.com/libsdl-org/SDL/releases/download/release-$env:SDL_VERSION/SDL2-devel-$env:SDL_VERSION-VC.zip" -o C:\SDL.zip
        Expand-Archive C:\SDL.zip -DestinationPath C:\SDL2
        echo NO not yet cached!

        ls C:\SDL2 -Include SDL.h -Recurse -Name
        ls C:\SDL2 -Include SDL2.lib -Recurse -Name
        ls C:\SDL2 -Include SDL2.dll -Recurse -Name
        ls C:\SDL2 -Include SDL2?Config.cmake -Recurse -Name

        echo ls C:\SDL2\SDL2-2.28.5\include -Name
        ls C:\SDL2\SDL2-2.28.5\include -Name
        echo ls C:\SDL2\SDL2-2.28.5\lib\x86 -Name
        ls C:\SDL2\SDL2-2.28.5\lib\x86 -Name
        echo ls C:\SDL2\SDL2-2.28.5\lib\x64 -Name
        ls C:\SDL2\SDL2-2.28.5\lib\x64 -Name
        echo ls C:\SDL2\SDL2-2.28.5\cmake -Name
        ls C:\SDL2\SDL2-2.28.5\cmake -Name

    - name: CMake configure --- Ninja, Msvc, Debug
      run: |
        echo cmake --preset Ninja-Msvc-Debug
        cmake --preset Ninja-Msvc-Debug

    - name: CMake build --- Ninja, Msvc, Debug
      run: |
        echo cmake --build --preset Ninja-Msvc-Debug
        cmake --build --preset Ninja-Msvc-Debug
